[build]
  # No build command needed for static HTML
  command = "echo 'Static site - no build required'"
  # Publish the root directory (not public)
  publish = "."
  
[build.environment]
  # No environment variables needed for static site
