[build]
  # No build command needed for static HTML
  command = "echo 'Static site - no build required'"
  # Publish the root directory
  publish = "."
  
[build.environment]
  # No environment variables needed for static site
  
# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
